//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EchoEntities : DbContext
    {
        public EchoEntities()
            : base("name=EchoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogSheet> LogSheets { get; set; }
        public virtual DbSet<LogSheetActivity> LogSheetActivities { get; set; }
        public virtual DbSet<MonthlyAssociationDue> MonthlyAssociationDues { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenantArchive> TenantArchives { get; set; }
        public virtual DbSet<TenantProfile> TenantProfiles { get; set; }
        public virtual DbSet<UnitProfile> UnitProfiles { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<WaterBilling> WaterBillings { get; set; }
    }
}
