//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<System.Guid> MonthlyAssocID { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual MonthlyAssociationDue MonthlyAssociationDue { get; set; }
    }
}
