//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public System.Guid ID { get; set; }
        public string Project { get; set; }
        public string UnitNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string Owner { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string Time { get; set; }
        public string Request1 { get; set; }
        public string Request2 { get; set; }
        public string Request3 { get; set; }
        public string Request4 { get; set; }
    
        public virtual UnitProfile UnitProfile { get; set; }
    }
}
