//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantArchive
    {
        public System.Guid ID { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<System.DateTime> StartOfOccupancy { get; set; }
        public Nullable<System.DateTime> EndOfOccupancy { get; set; }
        public string NatureOfOccupancy { get; set; }
        public Nullable<System.Guid> TenantID { get; set; }
    
        public virtual UnitProfile UnitProfile { get; set; }
    }
}
