//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherOccupants
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TenantProfileID { get; set; }
        public string FullName { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual TenantProfile TenantProfile { get; set; }
    }
}
