//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterBilling
    {
        public System.Guid ID { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string CurrentReading { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> OverdueAmount { get; set; }
        public Nullable<decimal> DisconnectionFee { get; set; }
    
        public virtual UnitProfile UnitProfile { get; set; }
    }
}
